### PR TITLE
Transfer antd menu children to items

### LINKED ISSUE #1645: [antd: Menu] `children` will be removed in next major version. Please use `items` instead
# Bug

**Describe the bug**
I did try to launch "https://geostyler.github.io/geostyler-beginner-workshop/" in my Laptop, when I run final step code I got warning message in my browser:

index.js:1437 
        
       Warning: [antd: Menu] `children` will be removed in next major version. Please use `items` instead.
 
        
       Warning: SubMenu should not leave undefined `key`.

        
       Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Wrap

        
         Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Wrap

Learn more about this warning here: https://reactjs.org/link/legacy-context
    at Wrap (http://localhost:3000/static/js/0.chunk.js:124041:40)

        
       Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Wrap

I'm going to know How can I solve these error messages? I did upgrade "antd" library to latest version, but they didn't appeared or didn't solved.

**To Reproduce**
1.I did launch final step in GeoStyler Beginner Workshop

**Expected behavior**
run without those error messages I mentioned above 

**Screenshots**
GeoStyler_bug

**Desktop (please complete the following information):**
 - OS: LMDE v5 X64
 - Browser : Microsoft Edge 
 - Version 101.0.1210.39 (Official build) (64-bit)

### PR DESCRIPTION
**Pull request by KaiVolland**
## Description

This transforms the children of the antd Menus to `items` as the approach of using children is deprecated in the newer antd versions

## Related issues or pull requests

Closes #1645

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Dependency updates
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe)
- [ ] I am unsure (we'll look into it together)

## Do you introduce a breaking change?

- [ ] Yes
- [x] No
- [ ] I am unsure (no worries, we'll find out)

## Checklist

- [x] I understand and agree that the changes in this PR will be licensed under the [BSD 2-Clause License](https://github.com/geostyler/geostyler/blob/master/)
- [x] I have followed the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/master/CONTRIBUTING.md)
- [x] The proposed change fits to the content of the [code of conduct](https://github.com/geostyler/geostyler/blob/master/CODE_OF_CONDUCT.md)
- [x] I have added or updated tests and documentation, and the test suite passes (run `npm test` locally)
- [x] I'm lost; why do I have to check so many boxes? Please help!

### CODE REVIEW

File: src/Component/Style/Style.tsx [hunk 1]
```diff
@@ -453,47 +455,46 @@ export class Style extends React.Component<StyleProps, StyleState> {
...
+      label: locale.addRuleBtnText,
+      icon: <PlusOutlined />
+    }, {
+      key: 'cloneRules',
+      label: locale.addRuleBtnText,
+      disabled: !allowClone,
+      icon: <CopyOutlined />
+    }, {
+      key: 'removeRule',
+      label: locale.addRuleBtnText,
```
Comment (annarieger) [inline src/Component/Style/Style.tsx:469]:
```suggestion
      label: locale.removeRulesBtnText,
```

**Review by annarieger — APPROVED** [review]
Please fix a misleading label, otherwise - 🔝
